# Generated by Django 3.0.9 on 2020-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mgb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=256, max_length=256),
        ),
    ]
