# Generated by Django 3.0.9 on 2020-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mgb', '0002_auto_20200804_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=256),
        ),
    ]
